tel: +44 (0) 7866 277 464
email: hello@matthewpassmore.co.uk
intro: I’m Matthew Passmore, an independent web consultant based in Cardiff, Wales. I help great organisations engage their online audience, and turn engagement into action.
cta:
  heading: Ready to kick-start your project?
  subheading: I deliver websites that convert engagement into action.
  linkText: Contact me
  linkTarget: "mailto:hello@matthewpassmore.co.uk"
